## Comando obrigatório
## Baixa a imagem do node com versão alpine (versão mais simplificada e leve)
FROM node:alpine
## Define o local onde o app vai ficar no disco do container
## Pode ser o diretório que você quiser
WORKDIR /usr/src/app
## Copia tudo que começa com package e termina com .json para dentro da pasta /usr/src/app
COPY package*.json ./
## Executa npm install para adicionar as dependências e criar a pasta node_modules
RUN npm i
## Copia tudo que está no diretório onde o arquivo Dockerfile está 
## para dentro da pasta /usr/src/app do container
COPY . .
## Container ficará ouvindo os acessos na porta 3000
EXPOSE 3333
## Não se repete no Dockerfile
## Executa o comando npm run migration:up para iniciar para criar as tabelas dentro do BD.
CMD ["npm", "run migration:up"]
#Normalmente esse dockerfile termina o npm run strat, mas ele sempre dava erro ao rodar um 'RUN run migration:up'
#Então decidi rodar o npm run start dentro do docker-compose
